@startuml
'https://plantuml.com/object-diagram

object "<u>nima:Instructor</u>" as instructor {
    firstName = "Nima"
    lastName = "Davarpanah"
    officeNumber = "3-2636"
}

object "<u>clean code:Textbook</u>" as textbook {
    author = "Robert Cecil Martin"
    publisher = "Pearson"
    title = "CleanCode:A Handbook of Agile Software Craftsmanship"
}

course o-- textbook
course o-- instructor
object "<u>cs5800:Course</u>" as course {
    name = "CS 5800 - Advanced Software Engineering"
}

@enduml
